exit code

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -61,6 +61,11 @@ runs:
       shell: bash
       run: |
         steampipe check "${{ inputs.run }}" --output=text --mod-location="/tmp/mod" --export=json --install-dir /tmp/sp_install_dir
+        # ignore the 1 exit code which gets set if there are only alarms
+        exit_code=$(echo $?)
+        if [[ exit_code -gt 1 ]];then
+          exit $exit_code
+        fi
     - name: Annotate
       shell: bash
       run: |
